import { viteBundler } from '@vuepress/bundler-vite';
import { defaultTheme } from '@vuepress/theme-default';
import { defineUserConfig } from 'vuepress';

export default defineUserConfig({
  lang: 'en-US',
  title: 'NestJS Boilerplate Documentation 🎉',
  description: 'An ultimate and awesome nodejs boilerplate wrote in typescript',
  base: process.env.DEPLOY_ENV === 'gh-pages' ? '/nestjs-arc/' : '/',
  bundler: viteBundler({
    viteOptions: {},
    vuePluginOptions: {},
  }),
  theme: defaultTheme({
    colorMode: 'light',
    sidebar: [
      // ['/', 'Introduction'],
      // '/docs/development',
      // '/docs/architecture',
      // '/docs/naming-cheatsheet',
      // '/docs/linting',
      // '/docs/troubleshooting',
      // Generated by Copilot
      {
        text: 'Guide',
        children: [
          '/',
          '/docs/development',
          '/docs/architecture',
          '/docs/naming-cheatsheet',
          '/docs/linting',
          '/docs/code-generation',
        ],
      },
    ],
  }),
});
